// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbrtwqzwoxmgdligujju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicnR3cXp3b3htZ2RsaWd1amp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzc4NDIsImV4cCI6MjA2NTkxMzg0Mn0.Tmv2s4r9ujh0oavQhlb9IG06qxCG-LV7ke1WMI7qeX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);